- src/chttpd_db.erl
> Add _local_docs and _design_docs handlers

- src/chttpd.erl
- src/chttpd_config_listener.erl
- src/chttpd_misc.erl
- src/chttpd_sup.erl
This PR should go with https://github.com/apache/couchdb-config/pull/2
> 2561 make config api consistent

- src/chttpd.erl
See enabling commit in couchdb-couch
COUCHDB-2752
> Validate host header

- src/chttpd.erl
- src/chttpd_rewrite.erl
This commit incorporates the original work by Ronny Pfannschmidt
<Ronny.Pfannschmidt@gmx.de> and myself for COUCHDB-1441 and COUCHDB-1651.
> Port max_rewrites to chttpd

- src/chttpd.erl
- src/chttpd_csrf.erl
> Call CouchDB's CSRF validation

- src/chttpd.erl
> Don't pass CSRF cookie to replicator

- src/chttpd_db.erl
> Capture histogram data for _bulk_requests

- src/chttpd_handlers.erl
> Fix 'override' and 'override default' functionality

- src/chttpd_auth.erl
- src/chttpd_handlers.erl
- src/chttpd_plugin.erl
- src/chttpd_sup.erl
This PR depends on apache/couchdb-couch-epi#8
> 2796 improve performance of providers function

- src/chttpd_db.erl
- test/chttpd_db_bulk_get_test.erl
Based on RCouch implementation by @benoitc.
COUCHDB-2310
> Implement /db/_bulk_get endpoint

- src/chttpd.erl
> Reject database names with path segments over 128 characters

- src/chttpd.erl
> Fix crypto deprecations

- src/chttpd_epi.erl
- src/chttpd_sup.erl
Depends on https://github.com/apache/couchdb-couch-epi/pull/12
> Update to new couch_epi API

- src/chttpd_db.erl
> Call parse_revs

- src/chttpd_auth.erl
This PR depends https://github.com/apache/couchdb-couch-epi/pull/15
The change would allow to chain multiple plugins.
> Use couch_epi:decide/5 for authenticate/authorize

- src/chttpd.erl
- src/chttpd_db.erl
> Backport content negotiation from couch_httpd_*

- src/chttpd_misc.erl
It's not actual anymore to have try/catch around replicate/2 as it never
throws any errors making catch block is actually unreached for
the specified clauses.
We also shouldn't repeat our self in error response rendering here.
> Update /_replicate handler and clean it from legacy decisions

- test/chttpd_db_test.erl
This patch explicitly configures an admin user and then makes all requests using that user's credentials. This approach continues to work under the CouchDB's security model, and also allows the tests to pass under Cloudant's security model.
COUCHDB-2865
BugzID: 55502
> Explicitly create admin user and authenticate requests in chttpd_db_test cases

- src/chttpd.erl
Provide information about actual request path when vhost feature is used.
> Set requested path parts

- src/chttpd_external.erl
- src/chttpd_rewrite.erl
> Rewrite via query server

- src/chttpd_misc.erl
Backport this feature by following [COUCHDB-2956](https://issues.apache.org/jira/browse/COUCHDB-2956)
> Cache favicon for one year

- src/chttpd.erl
- src/chttpd_plugin.erl
- test/chttpd_plugin_tests.erl
This is a companion PR for https://github.com/apache/couchdb-couch/pull/150
> 2966 before response hook

- src/chttpd_auth_cache.erl
> tolerate failure when inserting auth ddoc

- src/chttpd.erl
Change the log format from `chttpd` to include username.
> 2973 log user

- src/chttpd_db.erl
- src/chttpd_external.erl
Fix compilation warnings
COUCHDB-2730
> Fix compilation warnings

- src/chttpd_misc.erl
The endpoint is using the same handler as a backdoor interface, which only works for the requests to a local $node. For rpc calls to the remote nodes, as it's done on `/_node` endpoints, `handle_node_req` handler is getting `{badrpc,{'EXIT',normal}}` response and fails with `invalid_ejson` exception.
The change splits stats gathering from stats responding, allowing to use former on both `/_node/$node/_system` and backend's `/_system`
This closes COUCHDB-3027
> Fix _node/$node/_system endpoint

- src/chttpd.erl
> Call appropriate sockname function for socket type

- src/chttpd.erl
> 3049 fix sockname

- src/chttpd_db.erl
> Implement clustered _compact endpoint

- src/chttpd_db.erl
> Fix eventsource timeout handling

- src/chttpd_db.erl
> Pass user context when opening doc in db_attachment_req

- src/chttpd_db.erl
when fabric workers timeout,
fabric:get_missing_revs returns {error,timeout}
this handles timeout errors
COUCHDB-3220
> handle timeout in _revs_diff

- src/chttpd_rewrite.erl
Fix related to issue https://issues.apache.org/jira/browse/COUCHDB-3254
> Fix missing ampersand in rewritten queries
