src/chttpd.erl, test/chttpd_error_info_tests.erl
This reverts changes made in 059229777 commit allowing chttpd to send
HTTP 500 errors in the same format as httpd does, e.g.:
{"error": "unknown_error", "reason": "function_clause", "ref": 100500}
COUCHDB-2538
=> Restore <<"unknown_error">> for HTTP 500 errors

src/chttpd.erl, src/chttpd_misc.erl
In order to avoid users shooting themselves in the foot by using
`/_config/` on a clustered CouchDB with a loadbalancer in front,
we remove it on `15984` - it will be available for single-node-
mode on the backdoor port (`15986`) or for users that are feeling
lucky which want to fire curl requests to every node.
It also allows Fauxton to detect if it is running on a the backdoor
port. Fauxton will - if it gets a 200 instead of a 404 - show the
config-section to the user.
COUCHDB-2601 COUCHDB-2390 COUCHDB-2343
=> Remove _config route on cluster

src/chttpd.erl, src/chttpd_misc.erl
I was thought that only Windows command line needs a ping-sleep hack. Don't think we need this one.
=> Remove /_sleep endpoint

src/chttpd_cors.erl
We do have headers' keys represented as either lists or binaries.
Make sure we don't crash on `string:to_lower`.
COUCHDB-2733
=> Account for binary keys for headers in CORS

src/chttpd.erl, src/chttpd_db.erl, src/chttpd_handlers.erl, src/chttpd_httpd_handlers.erl, src/chttpd_sup.erl
Use `couch_epi` to implement dynamic http endpoint handlers.
The application which wishes to add dynamic endpoint would
have to do following:
1. Add a child into application supervisor
chttpd_handler:registration_childspec(
myapp, myapp_httpd_handlers)
2. Provide `myapp_httpd_handlers` callback module
-module(myapp_httpd_handlers).
-export([url_handler/1, db_handler/1, design_handler/1]).
url_handler(<<"_foo">>) -> fun myapp_httpd:handle_foo_req/1;
url_handler(_) -> no_match.
db_handler(<<"_bar">>) -> fun myapp_httpd:handle_bar_req/2;
db_handler(_) -> no_match.
design_handler(_) -> no_match.
=> Dynamic http endpoint handlers

src/chttpd_handlers.erl
There are two kinds of overrides:
- overriding regular endpoint
- overriding default handler (such as chttpd_db:handle_request/1)
Therefore there are two distinct options for overriding.
url_handler(<<"_all_dbs">>) ->
{override, fun mymodule:handle_all_dbs_req/1};
url_handler(_) ->
{default, fun mymodule:handle_request/1};
=> Support endpoint overriding

src/chttpd.erl
`invalid_bind_address` error is more helpful than `badmatch` from deeps of mochiweb internals.
=> Ensure that provided bind_address is correct

src/chttpd.erl, src/chttpd_db.erl, src/chttpd_misc.erl, src/chttpd_show.erl, src/chttpd_view.erl
validate that all POST requests with json body must have also have valid
json header: {"Content-Type": "application/json"}
This ensures a basic protection against CSRF
JIRA: COUCHDB-2775
=> check POST requests for valid json header

src/chttpd.erl, test/chttpd_error_info_tests.erl
Now they return 500. Since there is nothing wrong on the server,
400 is more appropriate.
For example, turns requests like these:
http -a adm:pass POST http://127.0.0.1:15984/db1/_all_docs  keys:='["1",2]'
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
{
"error": "2",
"reason": "{illegal_docid,2}"
}
Into:
http -a adm:pass POST http://127.0.0.1:15984/db1/_all_docs  keys:='["1",2]'
HTTP/1.1 400 Bad Request
Content-Type: application/json
{
"error": "illegal_docid",
"reason": 2
}
COUCHDB-2815
=> POST to /{db}/_all_docs with invalid keys should return 400

src/chttpd_handlers.erl
`provider` function is no longer needed since providers defined by
couch_epi_plugin behaviour.
=> Remove chttpd_handlers:provider

src/chttpd.erl, src/chttpd_test_util.erl, test/chttpd_handlers_tests.erl
COUCHDB-2666
Reintroduce https://github.com/apache/couchdb-chttpd/pull/35 changes since issue was not fixed.
=> Escape database name on POST /_replicate

src/chttpd_db.erl
This also fixes bug that existed in 1.x when escape sequence
represented in uppercase: then we send wrong Location header
back to user causing HTTP 404 result.
COUCHDB-2674
=> Restore HTTP 301 response for /db/_design%2fddoc/* resources

src/chttpd_db.erl
This assumes Last-Event-ID header value to be opaque.
COUCHDB-2858
=> Fix Last-Event-ID header handling for db changes feed

src/chttpd_db.erl
This fixes the issue that by setting a random ETag header, we implicitly
promised that there's a chance of a cache hit where there was no chance.
For 2.0, we simply remove the random ETag without replacement, in order
to not accidentally cause useless cache bloat in clients.
COUCHDB-2859
=> Don't set random ETag header for `_all_docs` view

src/chttpd_db.erl, src/chttpd_view.erl
This fixes an issue that was introduced with 72258e2 and e5b1aee.
Background:
Although all things still seemed to work, each request to a view
generated an exception with the following stack trace:
```
exception error: undefined function vacc:get/2
in function  chttpd:result/2 (src/chttpd.erl, line 297)
in call from chttpd:handle_request_int/1 (src/chttpd.erl, line 276)
in call from mochiweb_http:headers/6 (src/mochiweb_http.erl, line 122)
```
=> Fix return types of responses to view requests

src/chttpd.erl
This refactoring fixes the handling of errors from before_request.
Unify how we deal with errors among before_request and handle_request.
=> Handle errors from before_request/after_request

src/chttpd_cors.erl, test/chttpd_cors_test.erl
This PR makes it possible to configure CORS to be able to use custom headers.
It mostly fixes already existing code. The only new addition is `exposed_headers` setting.
The supported configuration is via `default.ini`:
```ini
[cors]
headers = "content-type, accept-ranges, ..."
methods = "COPY, DELETE, ...."
exposed_headers = "extra, accept-ranges, etag, server, ..."
```
=> Improve cors support

test/chttpd_plugin_tests.erl
This fixes the problem with chttpd_plugin_tests. Previously following would fail:
```
make eunit apps=chttpd tests=callback_test,error_info_test
```
In order to test this PR you would need to add https://github.com/apache/couchdb-erlang-tests/pull/1 as a dependency in `rebar.config.script`. You might need to add the app into `rel/reltool.config` as well.
=> Use couch_tests applications for chttpd_plugin_tests

include/chttpd.hrl, src/chttpd.erl
This makes chttpd to raise `400 Bad Request` error in case provided URL consist "%" character that not followed by two hex characters as required by RFC 2141.
Related issue: COUCHDB-2748
=> Reject incorrectly encoded urls

src/chttpd_view.erl
When `multi_query_view` is calling `chttpd:end_delayed_json_response/1` it is passing it the response it received from query_view's `#vacc`, which means it'll get back a response record and not `#vacc`.
COUCHDB-3031
=> Don't expect #vacc as a response of end_delayed_json_response in multi_query_view

src/chttpd_view.erl
Parameters in `multi_query_view` got decoded before parsing as part of reading POST's json body. This makes `parse_params` to skip double parsing and allows to use complex view keys in multi query payload.
COUCHDB-3031
=> Don't try to decode params in multi_query_view

src/chttpd.erl
There is no reason to pass {unknown_error, Error} to plugin and force it to
implement a match on that tuple. We should pass the Error itself and let
the plugin decide what to do with it.
=> Do not pass unknown_error atom to plugin

src/chttpd_auth_cache.erl
We send start_listener event from init to make sure we call
ensure_auth_ddoc_exists as soon as we can. Rather then calling it on
listener restart.
COUCHDB-3000
=> Inject _design/_auth on auth_cache startup

src/chttpd_auth_cache.erl
There's no need to end and restart the changes feed listener on every
heartbeat, so don't do that.
COUCHDB-3054
=> Don't end changes feed listener on heartbeat

src/chttpd.erl
Patch suggested by Ilya.
COUCHDB-3084
=> Don't set "authenticated" if party_mode_handler sets user context

src/chttpd_db.erl
Currently _view_cleanup endpoint is not cluster aware, only deletes
indexes on the node that gets the request. This will make it cluster
aware, deleting unused indexes on all nodes.
JIRA: COUCHDB-2779
=> make _view_cleanup endpoint cluster aware

src/chttpd_db.erl
In CouchDB 2.0, instance_start_time is always 0.
This means that when generating ETag values derived
from the database info object, the same ETags can be
incorrectly deemed valid between different database
instances with the metadata.
To avoid this we can incorporate the unique shard
suffix for the database instance when generating
the current ETag value.
COUCHDB-3017
=> use shard suffix when generating _changes ETag

src/chttpd_auth_cache.erl
This warning is tripped primarily when an admin is defined in local.ini
and has no associated _users document. This can happen fairly often in
development and testing setups, meaning that every other line in the
logfile is "no record of user admin".
The right thing to do here might be to check if the currently defined
user is a local admin and only complain in that situation, but presently
chttpd only directly depends on couch_auth_cache and to do so would 
require unencapsulating how couch_auth_cache handles ini file defined
admin users vs. authentication database users, which feels wrong.
Change suggested by @janl in #couchdb-dev IRC.
=> Drop logging level for "no record of user %s"

src/chttpd_cors.erl, test/chttpd_cors_test.erl
When "Access-Control-Request-Headers" is empty, return an empty
"Access-Control-Allow-Headers" in the response. This is the same
behaviour as when the "Access-Control-Request-Headers" header is
omitted from the request entirely.
Fixes COUCHDB-3090
=> Handle empty "Access-Control-Request-Headers" header

src/chttpd.erl
Three properties had their defaults changed to a value that
couch_util:parse_terms throws up on.
`"nil"` was changed to `undefined` in COUCHDB-2561 as part of normalising
the config API. The change from list to atom was a mistake.
COUCHDB-3162
=> Fix SSL defaults

src/chttpd_external.erl
When any error happen on an underlying socket mochiweb uses
exit(normal). Add catch for exit:normal and convert it to
exit({bad_request, <<"Incomplete">>}).
COUCHDB-3158
=> Handle disconnect when receiving body

src/chttpd_db.erl
Previously multipart/related PUT requests didn't check maximum request sizes.
This commit checks content-length and compares that with the maximum.
This means keeping the current "semantics" of max_document_size which actually
means "max request size". But this makes the check more efficient and can
be done earlier in request processing time.
PR depends on https://github.com/apache/couchdb-couch/pull/201 make sure to
merge that one first if accepted.
Jira: COUCHDB-3174
=> Add max_document_size checking for multipart PUT requests

src/chttpd.erl
The wrong status code is returned when creating or updating a document
with an invalid key.
Returns:
{u'reason': u'Bad special document member: _invalid_key', u'error':
u'doc_validation'}
HTTPError: 500 Server Error: Internal Server Error
Expected: 400 Bad Request error
COUCHDB-3222
=> HTTP code 500 instead of 400 for invalid key during document creation

src/chttpd_cors.erl, test/chttpd_cors_test.erl
Header `"Access-Control-Max-Age"` used by a browser to define for how long to keep preflight request's response cached.
This fix makes this parameter configurable through config section `[cors]`, attribute `max_age`.
=> Fix CORS max_age configuration parameter

src/chttpd_misc.erl, test/chttpd_welcome_test.erl
This could help users quickly discover the presence of an API or mode of
operation.
Jira: COUCHDB-3180
=> Add ability to return a "features" list in the server's welcome message.

src/chttpd_db.erl
Previously original `Db` record was kept on `filter_fun` tuple in `#changes_args` and passed to the filters. Now we are throwing it away and including `Db` record build in fabric, which has `user_ctx` stripped from it. As a result `UserCtx` object passed to the filter functions in ddoc is missing user's name and role.
The fix includes original `user_ctx` into db open parameters, so `Db` record build in fabric will have it properly set.
COUCHDB-3233
=> Include user_ctx in db open options

src/chttpd.erl
The fabric returns errors as {Class, Reason, Stack}
(see fabric_util:error_info/2).
Add the clause to error_info to handle it.
COUCHDB-3195
=> Handle error terms from fabric

src/chttpd_show.erl
This was not ported to chttpd and so wasn't really fixed in 2.0
COUCHDB-1447
=> Merge default update response headers with custom ones

src/chttpd.erl, src/chttpd_db.erl, test/chttpd_open_revs_error_test.erl
We currently don't have error clauses when calling fabric:open_revs. This PR adds these clauses in the general case and also introduces a new 503 response for https://github.com/apache/couchdb-fabric/pull/86.
=> Add Error Clause  For fabric:open_revs calls

test/chttpd_db_bulk_get_test.erl
The tests in chttpd_db_bulk_get_test do not start config app.
The change in https://github.com/apache/couchdb-couch/pull/226
introduces call to config app.
Make sure we mock config so the tests pass.
COUCHDB-3293
=> Mock config module in tests

src/chttpd.erl, src/chttpd_external.erl
This PR serves to consolidate ideas from https://github.com/apache/couchdb-chttpd/pull/114 (the discussion got a little long and convoluted) and to finalize implementation details.
**Background**
Sometimes users want to limit the actual document size of various requests. Currently, our ```max_document_size``` is a misnomer. It's actually the request body of the http request. So ```_bulk_docs``` requests with multiple docs or docs with attachments would still count within this ```max_document_size``` parameter. The name is misleading. 
**Requirements**
This feature contains the following requirements:
R1) Use config parameter names that actually reflect their intentions.
R2) Prevent DDOS attacks. 
R3) Do not allow loopholes for users to bypass the restriction and thereby create weird …
=> Introduce max_http_request_size to replace max_document_size
